export const labelMap = {
  // Math
  Calculus: '高等数学',
  高等数学: '高等数学',
  Integral: '高等数学',
  Integrals: '高等数学',
  'Limits & Continuity': '高等数学',
  'Mean Value Theorems': '高等数学',
  'Multivariable Calculus': '高等数学',
  'Linear Algebra': '线性代数',
  线性代数: '线性代数',
  Matrices: '矩阵运算',
  Eigenvalues: '特征值与特征向量',
  Probability: '概率与统计',
  概率与统计: '概率与统计',
  'Differential Equations': '常微分方程',
  'Exam Summary': '冲刺总结',
  'Exam Year': '真题年份',
  Toolkit: '解题工具',
  'Vector Calculus': '向量与空间解析几何',
  'Infinite Series': '无穷级数',
  'Quadratic Forms': '二次型',
  'Random Variables': '随机变量',
  Estimation: '数理统计',
  'Limit Theorems': '极限定理',
  Mock: '模拟卷',
  // CS 408
  'Data Structures': '数据结构',
  'Data Structure': '数据结构',
  'Operating Systems': '操作系统',
  'Computer Organization': '计算机组成原理',
  'Computer Network': '计算机网络',
  'Computer Networks': '计算机网络',
  'Linear Lists': '线性表',
  'Stack & Queue': '栈与队列',
  Trees: '树与二叉树',
  Graphs: '图论',
  Graph: '图论',
  'Search & Sort': '查找与排序',
  Hash: '散列',
  'Graph Applications': '图的应用',
  Heap: '堆',
  'Disjoint Set': '并查集',
  Strings: '字符串算法',
  CPU: '处理机',
  Memory: '存储系统',
  'Memory Management': '存储管理',
  'Process Management': '进程与线程',
  'File Management': '文件管理',
  'Application Layer': '计算机网络',
  'Transport Layer': '计算机网络',
  'Data Link': '计算机网络',
  Routing: '路由协议',
  Security: '网络安全',
  Overview: '网络体系结构',
  'Network Layer': '网络层',
  Threads: '线程',
  'File Systems': '文件系统',
  Storage: '存储系统',
  Compiler: '编译原理',
  'Lexical Analysis': '词法分析',
  'Syntax Analysis': '语法分析',
  'Intermediate Code': '中间代码',
  'Code Generation': '代码生成',
  Pipeline: '流水线',
  Cache: '高速缓存',
  'I/O': '输入输出',
  // Politics
  'Ma Yuan': '马克思主义原理',
  马原: '马克思主义原理',
  'Mao Zhong Te': '毛中特',
  毛中特: '毛泽东思想和中国特色社会主义理论体系',
  'Mao Zedong Thought': '毛泽东思想',
  'Xi Thought': '思想',
  时政: '时事政治',
  'Current Affairs': '时事政治',
  'Shi Gang': '近代史纲要',
  史纲: '近代史纲要',
  History: '近代史纲要',
  Ideology: '思想道德与法治',
  思修: '思想道德与法治',
  // English
  Translation: '翻译',
  Vocabulary: '词汇',
  Reading: '阅读',
  Writing: '写作',
  Grammar: '语法',
  Listening: '听力',
  Cloze: '完形填空',
}

export const translateLabel = (text) => {
  const key = (text || '').trim()
  return labelMap[key] || key
}
